### PR TITLE
Update OvenItemHandler.java

### PR DESCRIPTION
**Pull request by HarbingerOfCrazy**
changed slots so automatic in/output should now work as intended

### CODE REVIEW

**Comment by HarbingerOfCrazy** [comment]
is also likely to break any offset fixes you made to the Oven GUI, cause this was likely the cause.
also can you add at least the Oven back into the JEI Catalyst for the connected recipes?

**Comment by Lance5057** [comment]
I'm not sure I understand what this is fixing.

**Comment by HarbingerOfCrazy** [comment]
the oven has 9 inventory slots for Ingrediens, the file specifies it has 6, ergo automatically inserted pans land in the 7th ingredient slot and it tries to extract the output from the 8th, so automation is broken, as i have nit compiled anything to test i am not sure whether this fixes anything, probably should have opened a issue first...

**Comment by Lance5057** [comment]
Open an issue or test, I'm not gonna accept an untested PR.

**Pull request closed without merging**
